sonar.projectKey=mon-erp-backend
sonar.projectName=Neura ERP Backend
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.language=py
sonar.python.version=3.11
sonar.host.url=http://neura-sonarqube:9000
sonar.login=sqp_3b5d46af80bd7a81b43c7cd7131871ba8fa0edb6
