// src/config/modules.js
// Configuration centralisée de TOUS les modules - Version complète

import { 
  DashboardOutlined, ShoppingOutlined, ShoppingCartOutlined,
  TeamOutlined, WalletOutlined, DatabaseOutlined,
  UserOutlined, ProjectOutlined, SettingOutlined,
  DashboardFilled, RobotFilled, FundFilled, SafetyCertificateFilled,
  RobotOutlined, FundOutlined, SafetyCertificateOutlined,
  ThunderboltOutlined, RiseOutlined, FallOutlined,
  BankOutlined, InsuranceOutlined, GlobalOutlined,CheckCircleOutlined,
  FileTextOutlined, ApiOutlined, LockOutlined,
  AppstoreOutlined, EuroOutlined, DollarOutlined,
  MedicineBoxOutlined, CustomerServiceOutlined, PhoneOutlined,
  CameraOutlined, ClockCircleOutlined, ScanOutlined,
  LineChartOutlined, WarningOutlined, BookOutlined,
  ApartmentOutlined, HeartOutlined, CarOutlined,
  SyncOutlined, CodeOutlined, GatewayOutlined,
  DeploymentUnitOutlined, PartitionOutlined, DotChartOutlined,
  NodeIndexOutlined, VideoCameraOutlined, MessageOutlined,
  CreditCardOutlined, SwapOutlined, FolderOutlined,
  CalendarOutlined, PercentageOutlined,
  TransactionOutlined, ReconciliationOutlined, AuditOutlined,
  SafetyOutlined, SecurityScanOutlined
} from '@ant-design/icons';
import React from 'react';

// Couleurs professionnelles

// ============================================
// TOUS LES MODÈLES - SOURCE UNIQUE DE VÉRITÉ
// ============================================

export const ALL_MODULES = [
  // === CORE BUSINESS (8 modules) ===
  { key: 'dashboard', icon: <DashboardOutlined />, iconFilled: <DashboardFilled />, label: 'Tableau de bord', path: '/dashboard', description: "Vue d'ensemble de l'activité avec indicateurs clés", color: 'var(--primary)', category: 'business', order: 1, isDefault: true, shortLabel: 'Dashboard', fields: 24, relations: ['Ventes', 'Achats', 'Clients'], usage: 95, tags: ['Core', 'Dashboard', 'Analytics'], version: '2.1.0', lastUpdate: '2024-02-15', author: 'Équipe Core' },
  { key: 'sale', icon: <ShoppingOutlined />, iconFilled: <ShoppingOutlined />, label: 'Ventes', path: '/sale', description: 'Gestion complète des ventes, commandes et devis', color: 'var(--success)', category: 'business', order: 2, isDefault: true, shortLabel: 'Ventes', fields: 32, relations: ['Clients', 'Produits', 'Factures'], usage: 92, tags: ['Commercial', 'Transactions'], version: '3.2.0', lastUpdate: '2024-02-10', author: 'Équipe Commerciale' },
  { key: 'purchase', icon: <ShoppingCartOutlined />, iconFilled: <ShoppingCartOutlined />, label: 'Achats', path: '/purchase', description: 'Gestion des achats, commandes fournisseurs et approvisionnements', color: 'var(--accent)', category: 'business', order: 3, isDefault: true, shortLabel: 'Achats', fields: 28, relations: ['Fournisseurs', 'Produits', 'Stock'], usage: 78, tags: ['Achats', 'Supply Chain'], version: '2.5.1', lastUpdate: '2024-02-05', author: 'Équipe Achats' },
  { key: 'crm', icon: <TeamOutlined />, iconFilled: <TeamOutlined />, label: 'CRM', path: '/crm', description: 'Gestion de la relation client, prospects et opportunités', color: 'var(--secondary)', category: 'business', order: 4, isDefault: true, shortLabel: 'CRM', fields: 36, relations: ['Clients', 'Ventes', 'Marketing'], usage: 88, tags: ['CRM', 'Relation client'], version: '4.0.2', lastUpdate: '2024-02-12', author: 'Équipe CRM' },
  { key: 'account', icon: <WalletOutlined />, iconFilled: <WalletOutlined />, label: 'Comptabilité', path: '/account', description: 'Gestion comptable, facturation, paiements et rapports financiers', color: 'var(--info)', category: 'business', order: 5, isDefault: true, shortLabel: 'Compta', fields: 42, relations: ['Factures', 'Clients', 'Fournisseurs'], usage: 85, tags: ['Finance', 'Comptabilité'], version: '3.8.0', lastUpdate: '2024-02-08', author: 'Équipe Finance' },
  { key: 'stock', icon: <DatabaseOutlined />, iconFilled: <DatabaseOutlined />, label: 'Stock', path: '/stock', description: 'Gestion des stocks, inventaires et mouvements de produits', color: '#e67e22', category: 'business', order: 6, isDefault: true, shortLabel: 'Stock', fields: 26, relations: ['Produits', 'Entrepôts', 'Mouvements'], usage: 82, tags: ['Logistique', 'Inventaire'], version: '2.3.4', lastUpdate: '2024-02-03', author: 'Équipe Logistique' },
  { key: 'hr', icon: <UserOutlined />, iconFilled: <UserOutlined />, label: 'RH', path: '/hr', description: 'Gestion des ressources humaines, employés, congés et paie', color: 'var(--warning)', category: 'business', order: 7, isDefault: true, shortLabel: 'RH', fields: 38, relations: ['Employés', 'Départements', 'Contrats'], usage: 76, tags: ['RH', 'Personnel'], version: '3.1.2', lastUpdate: '2024-01-28', author: 'Équipe RH' },
  { key: 'project', icon: <ProjectOutlined />, iconFilled: <ProjectOutlined />, label: 'Projets', path: '/project', description: 'Gestion de projets, tâches, ressources et suivi', color: 'var(--primary-light)', category: 'business', order: 8, isDefault: true, shortLabel: 'Projets', fields: 34, relations: ['Tâches', 'Ressources', 'Clients'], usage: 71, tags: ['Gestion', 'Projets'], version: '2.7.1', lastUpdate: '2024-01-20', author: 'Équipe Projets' },

  // === IA GÉNÉRATIVE (2 modules) ===
  { key: 'ai-report-generator', icon: <FileTextOutlined />, iconFilled: <FileTextOutlined />, label: 'Génération Auto de Rapports IA', path: '/ai/report-generator', description: 'Créez des rapports complexes en langage naturel. L\'IA analyse vos données et génère des insights clés avec visualisations intelligentes.', badge: 'IA Générative', badgeColor: '#667eea', color: '#667eea', category: 'ai_generative', order: 1, isDefault: false, shortLabel: 'Rapports IA', fields: 56, relations: ['Toutes données ERP', 'KPIs', 'Historique'], usage: 97, tags: ['IA', 'Rapports', 'NLP', 'LLM'], version: '1.0.0', lastUpdate: '2024-03-20', author: 'Équipe IA' },
  { key: 'ai-quote-generator', icon: <DollarOutlined />, iconFilled: <DollarOutlined />, label: 'Génération Auto de Devis IA', path: '/ai/quote-generator', description: 'Générez des devis professionnels en une seconde. L\'IA comprend le contexte métier et personnalise chaque document.', badge: 'IA Générative', badgeColor: '#52c41a', color: '#52c41a', category: 'ai_generative', order: 2, isDefault: false, shortLabel: 'Devis IA', fields: 48, relations: ['Clients', 'Produits', 'Tarifs'], usage: 98, tags: ['IA', 'Devis', 'Génération Auto'], version: '1.0.0', lastUpdate: '2024-03-20', author: 'Équipe IA' },

  // === SUPPORT IA (2 modules) ===
  { key: 'ticket-auto-resolve', icon: <CustomerServiceOutlined />, iconFilled: <CustomerServiceOutlined />, label: 'Ticket Support Auto-Résolu', path: '/support/auto-resolve', description: 'Moteur de résolution intelligent qui analyse la documentation technique et l\'historique des tickets.', badge: 'RAG Avancé', badgeColor: '#1890ff', color: '#1890ff', category: 'ai_support', order: 1, isDefault: false, shortLabel: 'Auto-Résolu', fields: 42, relations: ['Tickets', 'Base connaissances'], usage: 96, tags: ['Support', 'RAG', 'Auto-résolution'], version: '1.0.0', lastUpdate: '2024-03-20', author: 'Équipe Support IA' },
  { key: 'call-analysis', icon: <PhoneOutlined />, iconFilled: <PhoneOutlined />, label: 'Analyse des Appels Clients', path: '/call-analytics', description: 'Extraction automatique d\'insights à partir des conversations téléphoniques.', badge: 'Speech-to-Text', badgeColor: '#722ed1', color: '#722ed1', category: 'ai_support', order: 2, isDefault: false, shortLabel: 'Call Analysis', fields: 38, relations: ['Appels', 'Transcriptions'], usage: 94, tags: ['Speech-to-Text', 'NLP', 'Sentiment Analysis'], version: '1.0.0', lastUpdate: '2024-03-19', author: 'Équipe Analytics' },

  // === ASSURANCE IA (6 modules) ===
  { key: 'claim-auto-declaration', icon: <CameraOutlined />, iconFilled: <CameraOutlined />, label: 'Déclaration Sinistre Automatisée', path: '/claims/declaration', description: 'Déclarez un sinistre en 30 secondes. L\'IA analyse les photos et extrait les données.', badge: 'Computer Vision', badgeColor: '#fa8c16', color: '#fa8c16', category: 'insurance_ai', order: 1, isDefault: false, shortLabel: 'Déclaration', fields: 52, relations: ['Sinistres', 'Contrats', 'Photos'], usage: 97, tags: ['Computer Vision', 'CNN', 'OCR'], version: '1.0.0', lastUpdate: '2024-03-18', author: 'Équipe Assurance IA' },
  { key: 'claim-real-time-tracking', icon: <ClockCircleOutlined />, iconFilled: <ClockCircleOutlined />, label: 'Suivi Sinistre en Temps Réel', path: '/claims/tracking/1', description: 'Timeline interactive avec estimations de délais et notifications intelligentes.', badge: 'RAG', badgeColor: '#13c2c2', color: '#13c2c2', category: 'insurance_ai', order: 2, isDefault: false, shortLabel: 'Suivi Sinistre', fields: 34, relations: ['Sinistres', 'Étapes'], usage: 95, tags: ['Suivi', 'Temps réel', 'RAG'], version: '1.0.0', lastUpdate: '2024-03-18', author: 'Équipe Assurance IA' },
  { key: 'damage-auto-estimation', icon: <EuroOutlined />, iconFilled: <EuroOutlined />, label: 'Estimation Auto des Dommages', path: '/claims/estimation', description: 'Estimation immédiate des dégâts et devis de réparation instantané.', badge: 'Deep Learning', badgeColor: '#52c41a', color: '#52c41a', category: 'insurance_ai', order: 3, isDefault: false, shortLabel: 'Estimation', fields: 46, relations: ['Photos', 'Tarifs réparation'], usage: 96, tags: ['Computer Vision', 'Deep Learning'], version: '1.0.0', lastUpdate: '2024-03-17', author: 'Équipe Assurance IA' },
  { key: 'coverage-recommendation', icon: <SafetyCertificateOutlined />, iconFilled: <SafetyCertificateFilled />, label: 'Recommandation Garanties Personnalisées', path: '/insurance/warranties', description: 'Proposez les garanties adaptées à chaque client pour un upsell intelligent.', badge: 'Collaborative Filtering', badgeColor: '#eb2f96', color: '#eb2f96', category: 'insurance_ai', order: 4, isDefault: false, shortLabel: 'Garanties', fields: 44, relations: ['Clients', 'Contrats', 'Garanties'], usage: 93, tags: ['Recommandation', 'Upsell'], version: '1.0.0', lastUpdate: '2024-03-17', author: 'Équipe Commerciale IA' },
  { key: 'loss-prevention', icon: <WarningOutlined />, iconFilled: <WarningOutlined />, label: 'Prévention des Sinistres', path: '/insurance/prevention', description: 'Conseils proactifs pour éviter les sinistres avec données météo et IoT.', badge: 'Predictive Analytics', badgeColor: '#ff4d4f', color: '#ff4d4f', category: 'insurance_ai', order: 5, isDefault: false, shortLabel: 'Prévention', fields: 38, relations: ['Météo', 'IoT'], usage: 88, tags: ['Prévention', 'IoT', 'Predictive Analytics'], version: '1.0.0', lastUpdate: '2024-03-16', author: 'Équipe Prévention IA' },
  { key: 'medical-assistant', icon: <MedicineBoxOutlined />, iconFilled: <MedicineBoxOutlined />, label: 'Assistant Médical Virtuel', path: '/health/assistant', description: 'Aide aux démarches médicales. L\'IA médicale oriente les patients et traite les documents.', badge: 'Medical NLP', badgeColor: '#2f54eb', color: '#2f54eb', category: 'insurance_ai', order: 6, isDefault: false, shortLabel: 'Médical', fields: 48, relations: ['Patients', 'Actes médicaux'], usage: 91, tags: ['Medical NLP', 'RAG', 'Santé'], version: '1.0.0', lastUpdate: '2024-03-16', author: 'Équipe Santé IA' },

  // === ENTREPRISE IA (2 modules) ===
  { key: 'omnichannel-portal', icon: <GlobalOutlined />, iconFilled: <GlobalOutlined />, label: 'Portail Client Omnicanal', path: '/customer/omnichannel', description: 'Expérience unifiée sur tous les canaux avec un profil client unique.', badge: 'Graph Database', badgeColor: '#722ed1', color: '#722ed1', category: 'enterprise', order: 1, isDefault: false, shortLabel: 'Omnicanal', fields: 64, relations: ['Clients', 'Canaux', 'Conversations'], usage: 98, tags: ['Omnicanal', 'Graph Database'], version: '1.0.0', lastUpdate: '2024-03-15', author: 'Équipe Expérience Client' },
  { key: 'robo-advisor', icon: <RobotFilled />, iconFilled: <RobotFilled />, label: 'Conseiller Financier Automatisé', path: '/finance/robo-advisor', description: 'Robo-advisor pour l\'optimisation dynamique des portefeuilles et l\'allocation d\'actifs.', badge: 'Reinforcement Learning', badgeColor: '#1890ff', color: '#1890ff', category: 'enterprise', order: 2, isDefault: false, shortLabel: 'Robo-Advisor', fields: 56, relations: ['Profil risque', 'Objectifs', 'Marchés'], usage: 94, tags: ['Robo-advisor', 'Reinforcement Learning'], version: '1.0.0', lastUpdate: '2024-03-15', author: 'Équipe Finance IA' },

  // === TECHNOLOGIES (2 modules) ===
  { key: 'performance-monitor', icon: <ThunderboltOutlined />, iconFilled: <ThunderboltOutlined />, label: 'Performance Monitor', path: '/performance/monitor', description: 'Monitoring des performances système en temps réel', color: '#1890ff', category: 'technology', order: 1, isDefault: false, shortLabel: 'Monitor', fields: 32, relations: ['Système', 'Logs'], usage: 93, tags: ['Monitoring', 'Performance'], version: '3.1.0', lastUpdate: '2024-02-12', author: 'Équipe Ops' },
  { key: 'blockchain', icon: <NodeIndexOutlined />, iconFilled: <NodeIndexOutlined />, label: 'Blockchain', path: '/blockchain', description: 'Traçabilité et blockchain pour les transactions sécurisées', color: '#2f54eb', category: 'technology', order: 2, isDefault: false, shortLabel: 'Blockchain', fields: 28, relations: ['Transactions', 'Certificats'], usage: 67, tags: ['Blockchain', 'Sécurité'], version: '1.5.2', lastUpdate: '2024-01-25', author: 'Équipe Blockchain' },

  // === BANQUE (6 modules) ===
  { key: 'credit-scoring', icon: <FundFilled />, iconFilled: <FundFilled />, label: 'Credit Scoring IA', path: '/banking/credit-scoring', description: 'Évaluation automatisée de la solvabilité des clients', badge: 'IA', badgeColor: '#1890ff', color: '#1890ff', category: 'banking', order: 1, isDefault: false, shortLabel: 'Credit Scoring', fields: 48, relations: ['Clients', 'Transactions'], usage: 96, tags: ['IA', 'Scoring', 'Risque'], version: '3.2.1', lastUpdate: '2024-02-15', author: 'Équipe Risk Management' },
  { key: 'fraud-detection-banking', icon: <SafetyCertificateFilled />, iconFilled: <SafetyCertificateFilled />, label: 'Détection Fraude Bancaire', path: '/banking/fraud-detection', description: 'Détection en temps réel des transactions frauduleuses', badge: 'Temps réel', badgeColor: '#f5222d', color: '#f5222d', category: 'banking', order: 2, isDefault: false, shortLabel: 'Fraude Bancaire', fields: 62, relations: ['Transactions', 'Comptes'], usage: 98, tags: ['IA', 'Fraude', 'Sécurité'], version: '4.0.2', lastUpdate: '2024-02-14', author: 'Équipe Sécurité Financière' },
  { key: 'aml-compliance', icon: <SafetyCertificateOutlined />, iconFilled: <SafetyCertificateOutlined />, label: 'Anti-Blanchiment (AML)', path: '/banking/aml', description: 'Détection des schémas de blanchiment d\'argent', color: '#722ed1', category: 'banking', order: 3, isDefault: false, shortLabel: 'Anti-Blanchiment', fields: 54, relations: ['Transactions', 'Clients'], usage: 94, tags: ['AML', 'Conformité'], version: '3.5.0', lastUpdate: '2024-02-10', author: 'Équipe Conformité' },
  { key: 'churn-prediction-banking', icon: <FallOutlined />, iconFilled: <FallOutlined />, label: 'Prédiction Attrition Clients', path: '/banking/churn-prediction', description: 'Prédiction des départs clients avec alertes précoces', color: '#ff4d4f', category: 'banking', order: 4, isDefault: false, shortLabel: 'Churn', fields: 42, relations: ['Clients', 'Transactions'], usage: 91, tags: ['Churn', 'Fidélisation'], version: '2.3.4', lastUpdate: '2024-02-03', author: 'Équipe Data Science' },
  { key: 'kyc-automation', icon: <ScanOutlined />, iconFilled: <ScanOutlined />, label: 'KYC Automatisé', path: '/banking/kyc', description: 'Vérification d\'identité et conformité KYC automatisée', badge: 'Nouveau', badgeColor: '#52c41a', color: '#52c41a', category: 'banking', order: 5, isDefault: false, shortLabel: 'KYC Auto', fields: 28, relations: ['Documents', 'Identité'], usage: 97, tags: ['KYC', 'OCR', 'Biométrie'], version: '2.5.2', lastUpdate: '2024-02-12', author: 'Équipe Onboarding' },
  { key: 'investment-recommendation', icon: <LineChartOutlined />, iconFilled: <LineChartOutlined />, label: 'Recommandation Investissements', path: '/banking/investment', description: 'Recommandations personnalisées d\'investissements', badge: 'Robo-Advisor', badgeColor: '#13c2c2', color: '#13c2c2', category: 'banking', order: 6, isDefault: false, shortLabel: 'Invest', fields: 46, relations: ['Profil risque', 'Produits'], usage: 89, tags: ['Investissement', 'Robo-Advisor'], version: '2.0.1', lastUpdate: '2024-02-08', author: 'Équipe Wealth Management' },

  // === ASSURANCE (5 modules) ===
  { key: 'claims-processing', icon: <FileTextOutlined />, iconFilled: <FileTextOutlined />, label: 'Traitement des Sinistres', path: '/insurance/claims', description: 'Automatisation du traitement des déclarations de sinistres', badge: 'Auto', badgeColor: '#fa8c16', color: '#fa8c16', category: 'insurance', order: 1, isDefault: false, shortLabel: 'Sinistres', fields: 46, relations: ['Sinistres', 'Contrats'], usage: 95, tags: ['Sinistres', 'Claims'], version: '4.2.1', lastUpdate: '2024-02-11', author: 'Équipe Sinistres' },
  { key: 'fraud-detection-insurance', icon: <SafetyCertificateFilled />, iconFilled: <SafetyCertificateFilled />, label: 'Détection Fraude Assurance', path: '/insurance/fraud-detection', description: 'Détection des fraudes à l\'assurance', badge: 'Anti-fraude', badgeColor: '#f5222d', color: '#f5222d', category: 'insurance', order: 2, isDefault: false, shortLabel: 'Fraude Assurance', fields: 52, relations: ['Sinistres', 'Contrats'], usage: 96, tags: ['Fraude', 'Sécurité'], version: '3.4.0', lastUpdate: '2024-02-09', author: 'Équipe Anti-Fraude' },
  { key: 'risk-scoring-insurance', icon: <FundOutlined />, iconFilled: <FundOutlined />, label: 'Scoring des Risques', path: '/insurance/risk-scoring', description: 'Scoring des risques clients pour la tarification', color: '#eb2f96', category: 'insurance', order: 3, isDefault: false, shortLabel: 'Risk Scoring', fields: 44, relations: ['Clients', 'Contrats'], usage: 93, tags: ['Scoring', 'Risque'], version: '3.1.2', lastUpdate: '2024-02-07', author: 'Équipe Actuariat' },
  { key: 'catastrophe-modeling', icon: <WarningOutlined />, iconFilled: <WarningOutlined />, label: 'Modélisation Catastrophes', path: '/insurance/catastrophe', description: 'Modélisation des risques de catastrophes naturelles', badge: 'Expert', badgeColor: '#fa8c16', color: '#fa8c16', category: 'insurance', order: 4, isDefault: false, shortLabel: 'Catastrophe', fields: 48, relations: ['Zones', 'Catastrophes'], usage: 76, tags: ['Catastrophe', 'Réassurance'], version: '3.5.2', lastUpdate: '2024-01-20', author: 'Équipe Réassurance' },
  { key: 'document-intelligence', icon: <BookOutlined />, iconFilled: <BookOutlined />, label: 'Intelligence Documentaire', path: '/shared/document-intelligence', description: 'Extraction et analyse automatique des documents', badge: 'OCR+', badgeColor: '#595959', color: '#595959', category: 'insurance', order: 5, isDefault: false, shortLabel: 'Doc Intel', fields: 28, relations: ['Documents', 'Contrats'], usage: 99, tags: ['OCR', 'NLP', 'Documents'], version: '4.0.3', lastUpdate: '2024-02-13', author: 'Équipe R&D' },

  // === ASSISTANTS IA (3 modules) ===
  { key: 'assistant-predict', icon: <RobotFilled />, iconFilled: <RobotFilled />, label: 'Assistant Prédictif', path: '/assistant/predict', description: 'Assistant IA spécialisé dans les prédictions', color: '#667eea', category: 'assistants', order: 1, isDefault: false, shortLabel: 'Predict', fields: 15, relations: ['IA', 'Prédictions'], usage: 85, tags: ['IA', 'Assistant', 'Prédictif'], version: '1.0.0', lastUpdate: '2024-03-01', author: 'Équipe IA' },
  { key: 'assistant-risk', icon: <SafetyCertificateFilled />, iconFilled: <SafetyCertificateFilled />, label: 'Assistant Risques', path: '/assistant/risk', description: 'Assistant IA pour l\'analyse des risques', color: '#f5222d', category: 'assistants', order: 2, isDefault: false, shortLabel: 'Risk', fields: 18, relations: ['IA', 'Risques'], usage: 82, tags: ['IA', 'Assistant', 'Risques'], version: '1.0.0', lastUpdate: '2024-03-01', author: 'Équipe IA' },
  { key: 'assistant-growth', icon: <RiseOutlined />, iconFilled: <RiseOutlined />, label: 'Assistant Croissance', path: '/assistant/growth', description: 'Assistant IA pour la stratégie commerciale', color: '#52c41a', category: 'assistants', order: 3, isDefault: false, shortLabel: 'Growth', fields: 16, relations: ['IA', 'Croissance'], usage: 88, tags: ['IA', 'Assistant', 'Croissance'], version: '1.0.0', lastUpdate: '2024-03-01', author: 'Équipe IA' },

  // === UTILITAIRES (5 modules) ===
  { key: 'ocr', icon: <ScanOutlined />, iconFilled: <ScanOutlined />, label: 'OCR Documents', path: '/ocr', description: 'Reconnaissance optique de caractères pour documents scannés', color: '#8c8c8c', category: 'utilities', order: 1, isDefault: false, shortLabel: 'OCR', fields: 18, relations: ['Documents', 'Fichiers'], usage: 72, tags: ['OCR', 'Documents'], version: '2.0.3', lastUpdate: '2024-01-30', author: 'Équipe Documents' },
  { key: 'documents', icon: <FileTextOutlined />, iconFilled: <FileTextOutlined />, label: 'Documents', path: '/documents', description: 'Gestion documentaire centralisée', color: 'var(--text-muted)', category: 'utilities', order: 2, isDefault: false, shortLabel: 'Documents', fields: 20, relations: ['Documents', 'Dossiers'], usage: 85, tags: ['Documents'], version: '3.0.0', lastUpdate: '2024-02-01', author: 'Équipe Bureau' },
  { key: 'calendar', icon: <CalendarOutlined />, iconFilled: <CalendarOutlined />, label: 'Calendrier', path: '/calendar', description: 'Agenda partagé', color: 'var(--text-muted)', category: 'utilities', order: 3, isDefault: false, shortLabel: 'Calendrier', fields: 15, relations: ['Événements'], usage: 70, tags: ['Calendrier'], version: '1.0.0', lastUpdate: '2024-01-15', author: 'Équipe Bureau' },
  { key: 'tasks', icon: <CheckCircleOutlined />, iconFilled: <CheckCircleOutlined />, label: 'Tâches', path: '/tasks', description: 'Gestion des tâches', color: 'var(--text-muted)', category: 'utilities', order: 4, isDefault: false, shortLabel: 'Tâches', fields: 12, relations: ['Utilisateurs'], usage: 75, tags: ['Tâches'], version: '1.0.0', lastUpdate: '2024-01-10', author: 'Équipe Bureau' },
  { key: 'settings', icon: <SettingOutlined />, iconFilled: <SettingOutlined />, label: 'Paramètres', path: '/settings', description: 'Configuration du système et paramètres utilisateur', color: 'var(--text-muted)', category: 'utilities', order: 5, isDefault: false, shortLabel: 'Settings', fields: 45, relations: ['Utilisateurs', 'Configuration'], usage: 100, tags: ['Configuration', 'Système'], version: '4.2.1', lastUpdate: '2024-02-14', author: 'Équipe Core' },

  // === API & INTÉGRATIONS (3 modules) ===
  { key: 'api-manager', icon: <ApiOutlined />, iconFilled: <ApiOutlined />, label: 'API Manager', path: '/api/manager', description: 'Gestion des API et endpoints', color: 'var(--secondary)', category: 'integrations', order: 1, isDefault: false, shortLabel: 'API Manager', fields: 22, relations: ['API', 'Endpoints'], usage: 79, tags: ['API', 'Intégration'], version: '2.0.0', lastUpdate: '2024-02-10', author: 'Équipe Technique' },
  { key: 'webhooks', icon: <SyncOutlined />, iconFilled: <SyncOutlined />, label: 'Webhooks', path: '/webhooks', description: 'Gestion des webhooks et événements', color: 'var(--success)', category: 'integrations', order: 2, isDefault: false, shortLabel: 'Webhooks', fields: 18, relations: ['Webhooks', 'Événements'], usage: 73, tags: ['Webhooks'], version: '1.5.0', lastUpdate: '2024-02-05', author: 'Équipe Technique' },
  { key: 'connectors', icon: <GatewayOutlined />, iconFilled: <GatewayOutlined />, label: 'Connecteurs', path: '/connectors', description: 'Connecteurs applicatifs', color: 'var(--accent)', category: 'integrations', order: 3, isDefault: false, shortLabel: 'Connecteurs', fields: 20, relations: ['Applications'], usage: 68, tags: ['Connecteurs'], version: '1.0.0', lastUpdate: '2024-01-20', author: 'Équipe Technique' },

  // === SÉCURITÉ (3 modules) ===
  { key: 'security', icon: <LockOutlined />, iconFilled: <LockOutlined />, label: 'Sécurité', path: '/security', description: 'Gestion de la sécurité et des accès', color: 'var(--error)', category: 'security', order: 1, isDefault: false, shortLabel: 'Sécurité', fields: 28, relations: ['Utilisateurs', 'Permissions'], usage: 99, tags: ['Sécurité'], version: '4.0.0', lastUpdate: '2024-02-15', author: 'Équipe Sécurité' },
  { key: 'compliance', icon: <SafetyCertificateOutlined />, iconFilled: <SafetyCertificateFilled />, label: 'Conformité', path: '/compliance', description: 'Gestion de la conformité RGPD et normes', color: 'var(--success)', category: 'security', order: 2, isDefault: false, shortLabel: 'Conformité', fields: 24, relations: ['Règles', 'Audits'], usage: 88, tags: ['Conformité', 'RGPD'], version: '2.3.0', lastUpdate: '2024-02-10', author: 'Équipe Conformité' },
  { key: 'audit', icon: <AuditOutlined />, iconFilled: <AuditOutlined />, label: 'Audit', path: '/audit', description: 'Traçabilité et audits', color: 'var(--info)', category: 'security', order: 3, isDefault: false, shortLabel: 'Audit', fields: 30, relations: ['Logs', 'Actions'], usage: 82, tags: ['Audit', 'Traçabilité'], version: '1.2.0', lastUpdate: '2024-02-01', author: 'Équipe Audit' },

  // === DASHBOARDS CLIENTS (3 modules) ===
  { key: 'banking-dashboard', icon: <BankOutlined />, iconFilled: <BankOutlined />, label: 'Dashboard Banque', path: '/banking-dashboard', description: 'Tableau de bord intelligent pour les banques', badge: 'Premium', badgeColor: '#722ed1', color: '#1890ff', category: 'dashboards', order: 1, isDefault: false, shortLabel: 'Bank Dash', fields: 78, relations: ['Transactions', 'Clients'], usage: 97, tags: ['Banque', 'Finance'], version: '2.1.0', lastUpdate: '2024-03-15', author: 'Équipe Finance' },
  { key: 'insurance-dashboard', icon: <InsuranceOutlined />, iconFilled: <InsuranceOutlined />, label: 'Dashboard Assurance', path: '/insurance-dashboard', description: 'Dashboard spécialisé pour les assurances', badge: 'Premium', badgeColor: '#722ed1', color: '#52c41a', category: 'dashboards', order: 2, isDefault: false, shortLabel: 'Insur Dash', fields: 82, relations: ['Sinistres', 'Contrats'], usage: 96, tags: ['Assurance', 'Sinistres'], version: '2.3.0', lastUpdate: '2024-03-14', author: 'Équipe Assurance' },
  { key: 'enterprise-dashboard', icon: <ApartmentOutlined />, iconFilled: <ApartmentOutlined />, label: 'Dashboard Entreprise', path: '/enterprise-dashboard', description: 'Tableau de bord complet pour les entreprises', badge: 'Premium', badgeColor: '#722ed1', color: '#722ed1', category: 'dashboards', order: 3, isDefault: false, shortLabel: 'Ent Dash', fields: 94, relations: ['Ventes', 'Finances'], usage: 99, tags: ['Entreprise', 'ERP'], version: '3.0.0', lastUpdate: '2024-03-16', author: 'Équipe Enterprise' },
];

// ============================================
// CATÉGORIES
// ============================================

export const CATEGORIES = [
  { key: 'business', label: '🏢 CORE BUSINESS', icon: <DashboardOutlined />, color: 'var(--primary-light)', order: 1 },
  { key: 'ai_generative', label: '🤖 IA GÉNÉRATIVE', icon: <RobotOutlined />, color: '#667eea', order: 2 },
  { key: 'ai_support', label: '🛠️ SUPPORT IA', icon: <CustomerServiceOutlined />, color: '#1890ff', order: 3 },
  { key: 'insurance_ai', label: '🛡️ ASSURANCE IA', icon: <CameraOutlined />, color: '#fa8c16', order: 4 },
  { key: 'enterprise', label: '🏭 ENTREPRISE', icon: <GlobalOutlined />, color: '#722ed1', order: 5 },
  { key: 'technology', label: '⚡ TECHNOLOGIES', icon: <ThunderboltOutlined />, color: '#1890ff', order: 6 },
  { key: 'banking', label: '🏦 BANQUE', icon: <BankOutlined />, color: '#1890ff', order: 7 },
  { key: 'insurance', label: '📄 ASSURANCE', icon: <InsuranceOutlined />, color: '#fa8c16', order: 8 },
  { key: 'assistants', label: '🎯 ASSISTANTS IA', icon: <RobotFilled />, color: 'var(--secondary-light)', order: 9 },
  { key: 'utilities', label: '⚙️ UTILITAIRES', icon: <SettingOutlined />, color: 'var(--text-muted)', order: 10 },
  { key: 'integrations', label: '🔌 API & INTÉGRATIONS', icon: <ApiOutlined />, color: 'var(--secondary)', order: 11 },
  { key: 'security', label: '🔒 SÉCURITÉ', icon: <LockOutlined />, color: 'var(--error)', order: 12 },
  { key: 'dashboards', label: '📊 DASHBOARDS', icon: <AppstoreOutlined />, color: '#722ed1', order: 13 },
];

// ============================================
// MODULES ACTIFS PAR DÉFAUT
// ============================================

export const DEFAULT_ACTIVE_MODULES = ['dashboard', 'sale', 'purchase', 'crm', 'account', 'stock', 'hr', 'project'];

// ============================================
// FONCTIONS UTILITAIRES
// ============================================

export const getModuleByKey = (key) => ALL_MODULES.find(m => m.key === key);
export const getModulesByCategory = (category) => ALL_MODULES.filter(m => m.category === category);
export const getActiveModulesDetails = (activeKeys) => activeKeys.map(key => getModuleByKey(key)).filter(Boolean);