"""Fix enum definitions and add missing models

Revision ID: 44222539b3ef
Revises: 1c6f63988cca
Create Date: 2026-03-21 15:44:09.505870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44222539b3ef'
down_revision: Union[str, None] = '1c6f63988cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
